<a href="https://colab.research.google.com/github/VasylKostyrko/ColabVerPro/blob/main/%D0%95%D0%BA%D1%81%D0%BF%D0%B5%D1%80%D1%82%D0%BD%D0%B8%D0%B9_%D0%BC%D0%B5%D1%82%D0%BE%D0%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Застосування експертного методу до аналізу ОПП**

# Завантаження даних з локального комп'ютера.
Файл *Експертний_метод_до_ОПП.xlsx*  формату MS Excell
<br>завантажуємо з локального комп'ютера.
<br>Неіснуюча "магічна" команда *cancel*  блокує відображення 16-ого вмісту,файлу.
<br>А блок *try-except* блокує появу помилки.

In [1]:
try:
  from google.colab import files
  files.upload()
  %%cancel
except Exception:
  next


Saving Експертний_метод_до_ОПП.xlsx to Експертний_метод_до_ОПП.xlsx


Дані завантажуємо з аркуша *Дані* файлу.

In [2]:
import pandas as pd
df = pd.read_excel('/content/Експертний_метод_до_ОПП.xlsx',
                   sheet_name = "Дані")

Переглянемо завантажені дані.
<br>NaN свідчить про відсутність даних у відповідній клітинці таблиці.


In [6]:
df

Бальна оцінка показників, надана здобувачами освітньо-професійних програм  \
0   Показники (фактори, що впливають на навчання з...                          
1               Недостатній рівень підготовки в школі                          
2   Недостатнє забезпечення навчально-методичною л...                          
3                                   Незручний розклад                          
4            Надмірний обсяг навчального навантаження                          
5           Необхідність поєднувати навчання і роботу                          
6    Розчарування в освітній програмі (спеціальності)                          
7                          Особиста неорганізованість                          
8                    Відсутність інтересу до навчання                          
9   Вплив з боку інших студентів, що пережкоджає п...                          
10            Відсутність перспектив працевлаштування                          

           Unnamed: 1         Unnamed: 2  Unnamed: 3  \
0   Комп’ютерні науки  Реклама у бізнесі  Менеджмент   
1                  32                 37          16   
2                  14                  6          19   
3                  22                 15          23   
4                  44                 18          14   
5                  10                 34          26   
6                  15                 17          13   
7                  23                  7          41   
8                  12                 14           5   
9                  35                 22          16   
10                  5                  8          39   

                          Unnamed: 4 Unnamed: 5 Unnamed: 6  
0   Логістика та менеджмент продажів    Туризм       Право  
1                                 25         13         52  
2                                 24         12         28  
3                                 17         30         20  
4                                 25         27         48  
5                                 50         46         35  
6                                 15         18         24  
7                                 34         36         20  
8                                 28         30          7  
9                                 18         14         33  
10                                43         30          9

Побудуємо і відобразимо масив *opp* назв освітньо-професійних програм.
<br>За допомогою об'єкта warnings усунемо попередження.

In [4]:
import warnings
warnings.filterwarnings("ignore")

ncol = 7
opp=df.iloc[0,1:ncol]
print(type(opp))
for j in range(ncol-1):
  print(opp[j])

<class 'pandas.core.series.Series'>
Комп’ютерні науки
Реклама у бізнесі
Менеджмент
Логістика та менеджмент продажів
Туризм 
Право


Побудуємо список *epn* назв експертних показників.

In [7]:
nrow = 12
epn = df.iloc[1:nrow-1,0]
print(type(epn))
for i in range(10):
  print(epn[i + 1])


<class 'pandas.core.series.Series'>
Недостатній рівень підготовки в школі
Недостатнє забезпечення навчально-методичною літературою (підручники, навчальні посібники, методичні вказівки)
Незручний розклад
Надмірний обсяг навчального навантаження
Необхідність поєднувати навчання і роботу
Розчарування в освітній програмі (спеціальності)
Особиста неорганізованість
Відсутність інтересу до навчання
Вплив з боку інших студентів, що пережкоджає прояву здібностей студента під час навчальних занять
Відсутність перспектив працевлаштування


Відобразимо масив значень експертних показників у вигляді двовимірного масиву Numpy.

In [8]:
epd = df.iloc[1:nrow -1, 1:ncol]
vpd = epd.values
print(type(vpd))
print(vpd)

<class 'numpy.ndarray'>
[[32 37 16 25 13 52]
 [14 6 19 24 12 28]
 [22 15 23 17 30 20]
 [44 18 14 25 27 48]
 [10 34 26 50 46 35]
 [15 17 13 15 18 24]
 [23 7 41 34 36 20]
 [12 14 5 28 30 7]
 [35 22 16 18 14 33]
 [5 8 39 43 30 9]]


# Розрахунок коефіцієнтів вагомості

Побудуємо список сум *sumopp* експертних показників.

In [10]:
allsum = 0
sumopp = []
for i in range(nrow-2):
  s = 0
  for j in range(ncol-1):
    d = vpd[i, j]
    s = s + d
  print(s, "-->", epn[i+1])
  sumopp.append(s)
  allsum = allsum + s

175 --> Недостатній рівень підготовки в школі
103 --> Недостатнє забезпечення навчально-методичною літературою (підручники, навчальні посібники, методичні вказівки)
127 --> Незручний розклад
176 --> Надмірний обсяг навчального навантаження
201 --> Необхідність поєднувати навчання і роботу
102 --> Розчарування в освітній програмі (спеціальності)
161 --> Особиста неорганізованість
96 --> Відсутність інтересу до навчання
138 --> Вплив з боку інших студентів, що пережкоджає прояву здібностей студента під час навчальних занять
134 --> Відсутність перспектив працевлаштування


Побудуємо список *weights* словників вагомості показників.

In [11]:
weights = []
for i in range(nrow - 2):
  s = sumopp[i] / allsum
  dict = {'ep':s, 'nep':epn[i + 1]}
  print(dict['ep'], "-->", dict['nep'])
  weights.append(dict)

0.12384996461429583 --> Недостатній рівень підготовки в школі
0.07289455060155697 --> Недостатнє забезпечення навчально-методичною літературою (підручники, навчальні посібники, методичні вказівки)
0.08987968860580325 --> Незручний розклад
0.12455767869780608 --> Надмірний обсяг навчального навантаження
0.14225053078556263 --> Необхідність поєднувати навчання і роботу
0.07218683651804671 --> Розчарування в освітній програмі (спеціальності)
0.11394196744515216 --> Особиста неорганізованість
0.06794055201698514 --> Відсутність інтересу до навчання
0.09766454352441614 --> Вплив з боку інших студентів, що пережкоджає прояву здібностей студента під час навчальних занять
0.09483368719037509 --> Відсутність перспектив працевлаштування


Впорядкуємо список словників *weights* за спаданням коефіцієнтів вагомості.

In [12]:
sorted_weights = sorted(weights, key=lambda x: x['ep'], reverse=True)
for i in range(nrow - 2):
  dict = sorted_weights[i]
  print(dict['ep'], "-->", dict['nep'])

0.14225053078556263 --> Необхідність поєднувати навчання і роботу
0.12455767869780608 --> Надмірний обсяг навчального навантаження
0.12384996461429583 --> Недостатній рівень підготовки в школі
0.11394196744515216 --> Особиста неорганізованість
0.09766454352441614 --> Вплив з боку інших студентів, що пережкоджає прояву здібностей студента під час навчальних занять
0.09483368719037509 --> Відсутність перспектив працевлаштування
0.08987968860580325 --> Незручний розклад
0.07289455060155697 --> Недостатнє забезпечення навчально-методичною літературою (підручники, навчальні посібники, методичні вказівки)
0.07218683651804671 --> Розчарування в освітній програмі (спеціальності)
0.06794055201698514 --> Відсутність інтересу до навчання


# **Ранжування**
Перетворимо масив Numpy в масив Series Pandas і проранжуємо його.
Параметр *strlen* обмежує довжину стрічок.

In [14]:
arv = []
for i in range(ncol-1):
  row = []
  for j in range(nrow-2):
    row.append(vpd[j][i])
  rv = pd.Series(row).rank(ascending=False)
  arv.append(rv)

arv - це масив рангів показників.
<br>Для компактного відображення даних введемо параметр *strlen*. Функція *cuts* обрізає рядки, якщо довжина перевищує *strlen*.
<br>Якщо *strlen* == 0,
тоді функція *cuts* не впливає на рядки.

In [15]:
params = {"strlen": 50}   # Довжина рядків обмежена 50 символами
# params = {"strlen": 0}  # Необмежена довжина рядків

In [16]:
def cuts(s):
  n = params["strlen"]
  res = s
  if n > 0 and len(s) > n:
      res = s[:n]
  return(res)

In [17]:
# from IPython.display import HTML, display
from tabulate import tabulate
tabledata = []
tablehead = ['Показник']
for i in range(ncol-1):
  s = cuts(opp[i])
  tablehead.append(s)
tabledata.append(tablehead)
for i in range(nrow-2):
  datarow = []
  s = cuts(epn[i+1])
  datarow.append(s)
  for j in range(ncol-1):
    r = arv[j][i]
    datarow.append(r)
  tabledata.append(datarow)
print(tabulate(tabledata, headers='firstrow'))

Показник                                              Комп’ютерні науки    Реклама у бізнесі    Менеджмент    Логістика та менеджмент продажів    Туризм     Право
--------------------------------------------------  -------------------  -------------------  ------------  ----------------------------------  ---------  -------
Недостатній рівень підготовки в школі                                 3                    1           6.5                                 5.5          9      1
Недостатнє забезпечення навчально-методичною літер                    7                   10           5                                   7           10      5
Незручний розклад                                                     5                    6           4                                   9            4      7.5
Надмірний обсяг навчального навантаження                              1                    4           8                                   5.5          6      2
Необхідність поєднувати навч

Ранжуємо сумарні показники. Причому, їх ранжуємо за спаданням.

In [18]:
stabledata = []
src = []
for i in range(nrow-2):
  rsum = 0
  for j in range(ncol-1):
    rsum += arv[j][i]
  src.append(rsum)
srv = pd.Series(src).rank(ascending=True)
stablehead = ['Показник','Сума', 'Ранг']
stabledata.append(stablehead)
for i in range(nrow-2):
  s = cuts(epn[i+1])
  srow = [s, src[i], srv[i]]
  stabledata.append(srow)
print(tabulate(stabledata, headers='firstrow'))

Показник                                              Сума    Ранг
--------------------------------------------------  ------  ------
Недостатній рівень підготовки в школі                 26       2
Недостатнє забезпечення навчально-методичною літер    44      10
Незручний розклад                                     35.5     7
Надмірний обсяг навчального навантаження              26.5     3.5
Необхідність поєднувати навчання і роботу             19       1
Розчарування в освітній програмі (спеціальності)      43       8.5
Особиста неорганізованість                            26.5     3.5
Відсутність інтересу до навчання                      43       8.5
Вплив з боку інших студентів, що пережкоджає прояв    31.5     5
Відсутність перспектив працевлаштування               35       6


# **Розрахунок коефіцієнтів Спірмена**

Округлення дійсних чисел визначає параметр *round*.
<br>Якщо цей параметр є цілим числом, тоді воно визначає кількість
десяткових цифр результату.
<br>Інакше дійсні числа не округлюються.

In [19]:
params["round"] = 2
# params["round"] = ""

Округлення реалізує функція *nround*.

In [20]:
def nround(x):
  n = params["round"]
  if type(n) is int:
    y = round(x, n)
    return(y)
  else:
    return(x)

Функція *spearman* визначає кофіцієнт Спірмена між рангами експертних оцінок ОПП номер  *n* та *m*.

In [23]:
def spearman(n, m):
  e1 = arv[n]
  e2 = arv[m]
  data = {'e1': e1, 'e2': e2}
  df = pd.DataFrame(data)
  spearman_corr = df['e1'].corr(df['e2'], method='spearman')
  # print(opp[n])
  # print(opp[m])
  rs = nround(spearman_corr)
  return rs

In [35]:
oppn = ['ОПП']
for i in range(1,ncol-1):
  oppn.append(opp[i])
aks = [oppn]
for i in range(ncol-2):
  rks = [opp[i]]
  for j in range(1, ncol-1):
    if j >= i+1:
      rs = spearman(i,j)
    else:
      rs = ""
    rks.append(rs)
  aks.append(rks)
# aks
print(tabulate(aks, headers='firstrow'))

ОПП                               Реклама у бізнесі    Менеджмент    Логістика та менеджмент продажів    Туризм       Право
--------------------------------  -------------------  ------------  ----------------------------------  ---------  -------
Комп’ютерні науки                 0.37                 -0.27         -0.46                               -0.4          0.56
Реклама у бізнесі                                      -0.3          -0.05                               -0.08         0.72
Менеджмент                                                           0.49                                0.47         -0.13
Логістика та менеджмент продажів                                                                         0.63         -0.1
Туризм                                                                                                                -0.41



#Розрахунок коефіцієнта конкордації Кенделла



In [71]:
import numpy as np

def kendall_concordance(ranks):
  m, n = ranks.shape
  mean_rank = np.mean(ranks, axis=0)
  ss = np.sum((ranks - mean_rank)**2)
  print(ss)
  res = 12 * ss / (m**2 * (n**3 - n))
  return res

In [78]:
np_arv = np.array(arv)
print(type(np_arv))
np_arv

<class 'numpy.ndarray'>


array([[ 3. ,  7. ,  5. ,  1. ,  9. ,  6. ,  4. ,  8. ,  2. , 10. ],
       [ 1. , 10. ,  6. ,  4. ,  2. ,  5. ,  9. ,  7. ,  3. ,  8. ],
       [ 6.5,  5. ,  4. ,  8. ,  3. ,  9. ,  1. , 10. ,  6.5,  2. ],
       [ 5.5,  7. ,  9. ,  5.5,  1. , 10. ,  3. ,  4. ,  8. ,  2. ],
       [ 9. , 10. ,  4. ,  6. ,  1. ,  7. ,  2. ,  4. ,  8. ,  4. ],
       [ 1. ,  5. ,  7.5,  2. ,  3. ,  6. ,  7.5, 10. ,  4. ,  9. ]])

In [79]:
concordance = kendall_concordance(np_arv)
print("Коефіцієнт конкордації:", concordance)

381.0
Коефіцієнт конкордації: 0.12828282828282828


In [76]:
transposed_matrix = np_arv.T
transposed_matrix

array([[ 3. ,  1. ,  6.5,  5.5,  9. ,  1. ],
       [ 7. , 10. ,  5. ,  7. , 10. ,  5. ],
       [ 5. ,  6. ,  4. ,  9. ,  4. ,  7.5],
       [ 1. ,  4. ,  8. ,  5.5,  6. ,  2. ],
       [ 9. ,  2. ,  3. ,  1. ,  1. ,  3. ],
       [ 6. ,  5. ,  9. , 10. ,  7. ,  6. ],
       [ 4. ,  9. ,  1. ,  3. ,  2. ,  7.5],
       [ 8. ,  7. , 10. ,  4. ,  4. , 10. ],
       [ 2. ,  3. ,  6.5,  8. ,  8. ,  4. ],
       [10. ,  8. ,  2. ,  2. ,  4. ,  9. ]])

In [77]:
np_arv = np.array(transposed_matrix)
concordance = kendall_concordance(np_arv)
print("Коефіцієнт конкордації:", concordance)

491.5
Коефіцієнт конкордації: 0.28085714285714286
